---
- name: Test connection to my servers
  hosts: all
  become: yes
  gather_facts: false
  
#   roles:
#    - { role: dock_compose, when ansible_system == "Linux"}

  tasks:

  - name: pull an image
    shell: docker pull 11051988/my_py_app:latest

     
    # docker_image:
    #  name: 11051988/my_py_app:latest
    #  source: pull
    # when: true

  - name: Create and start a data container
    docker_container:
     name: flassk-app2
     image: 11051988/my_py_app:latest
     state: started
     restart: yes
     ports:
          - "80:5000"