---
- name: Test connection to my servers
  hosts: all
  become: yes
  gather_facts: false
  
  roles:
   - { role: dock_compose, when ansible_system == "Linux"}




  tasks:
  - name: pull an image
    docker_image:
     name: 11051988/my_py_app
     source: pull