name: CI/CD - DOS07

env:
  IMAGE_NAME: "my_py_app"
  DOCKER_USER: ${{ secrets.DOCKER_USER }}
  DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
  AWS_ACCESS_KEY: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_KEY: ${{ secrets.AWS_SECRET_KEY_ID }}   
  PLAYBOOK: "app_deploy_to_ec2.yml"
  AWS_EC2_KEY: ${{ secrets.AWS_EC2_KEY }}   
on:
  push:
    branches:
      - main
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
     - name: 'Checkout'
       uses: actions/checkout@main
       

     - name: 'docker login'
       run: docker login -u  $DOCKER_USER -p $DOCKER_PASSWORD


     - name: "Build"
       run: docker build -t $DOCKER_USER/$IMAGE_NAME:1.0 .
            
       
     - name: "Push"
       run: docker push $DOCKER_USER/$IMAGE_NAME:1.0

     - name: "ansible --version"
       run: ansible --version
  CD:
    name: CD
    needs: [CI]
    runs-on: ubuntu-latest
   
    steps:
    - name: 'Checkout'
      uses: actions/checkout@main

    - name: Decrypt Pem
      run: gpg --quiet --batch --yes --decrypt --passphrase="$LARGE_SECRET_PASSPHRASE" --output $HOME/secrets/my_private_key.pem my_private_key.pem.gpg
      env:
      LARGE_SECRET_PASSPHRASE: ${{ secrets.LARGE_SECRET_PASSPHRASE }}  

    - name: RUN ansible
      run: ansible-playbook  ${{ env.PLAYBOOK }} -i hosts --private-key aws_test.pem
      
      
      
      
      
      
      
      
      
      
      
    # - name: RUN ansible
    #   uses: dawidd6/action-ansible-playbook@v2
    #   with:
    #     playbook: ${{ env.PLAYBOOK }}
    #     #playbook: app_deploy_to_ec2.yml
    #     #directory: /.
    #     key: ${{ env.AWS_EC2_KEY }}
    #     inventory: |
    #      [all]
    #      appserver ansible_host=18.195.101.221 ansible_user=ubuntu ansible_ssh_private_key=${{ env.AWS_EC2_KEY }}
     
    #     options: |
    #       -- inventory hosts

   # ansible_ssh_private_key=${{ env.AWS_EC2_KEY }}