name: CI/CD - DOS07

env:
  IMAGE_NAME: "my_py_app"
  DOCKER_USER: ${{secrets.DOCKER_USER}}
  DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
  AWS_ACCESS_KEY: ${{secrets.AWS_ACCESS_KEY_ID}}
  AWS_SECRET_KEY: ${{secrets.AWS_SECRET_KEY_ID}}   

on:
  push:
    branches:
      - main
jobs:
  CI:
    name: CI
    runs-on: ubuntu-latest
    
    steps:
     - name: 'Checkout'
       uses: actions/checkout@main
       

     - name: 'docker login'
       run: docker login -u  $DOCKER_USER -p $DOCKER_PASSWORD


     - name: "Build"
       run: docker build -t $DOCKER_USER/$IMAGE_NAME:1.0 .
            
       
     - name: "Push"
       run: docker push $DOCKER_USER/$IMAGE_NAME:1.0
  CD:
    name: CD
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      uses: appleboy/ssh-action@master
      with:
        host: ${{ env.HOST}}
        username: ${{ env.USERNAME }}
        password: ${{ secrets.PASSWORD }}
        port: ${{ secrets.PORT }}
        script: whoami
